### ISSUE TITLE
any way to make the twm-conky Weather Widget display current outside weather?

### ISSUE THREAD

**Issue by Kolosman** [pdn6606/TWM-xfce#1]

**Comment by Kolosman** [comment]
i figured it out, you put [location] and _THEN_ ?0ATQ. but i had to read the documentation for it so, yeah
maybe if you ever make another commit to this, add how to configure it

**Comment by pdn6606** [comment]
Thank you for the suggestion. I have updated the README.md to include how to configure the location.
